# Generated by Django 4.1.7 on 2023-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="in_progress",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
