# Generated by Django 4.1.7 on 2023-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_in_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
