# Generated by Django 4.1.7 on 2023-03-29 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_in_progress_alter_task_is_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"default_related_name": "tasks"},
        ),
    ]
