# Generated by Django 4.1.7 on 2023-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
