# Generated by Django 4.1.7 on 2023-03-31 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_completed_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"default_related_name": "tasks", "ordering": ["deadline"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.position",
            ),
        ),
    ]
